/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliherbalpos;

import javax.swing.JOptionPane;

/**
 *
 * @author gen781
 */
public class formUtama extends javax.swing.JFrame {

    /**
     * Creates new form formUtama
     */
    public formUtama() {
        initComponents();     
        setLocationRelativeTo(this);
        menuLogout();
        menuLogin();
    }

    private void menuLogin(){
        if(login.hakakses.equals("Pemilik")){
            mnuFile.setEnabled(true);
            mnuMaster.setEnabled(true);
            mnuTransaksi.setEnabled(true);
            mnuLaporan.setEnabled(true);
            mnuAbout.setEnabled(true);
        }
        else{
            mnuFile.setEnabled(true);
            mnuMaster.setEnabled(true);
            itmBarang.setVisible(false);
            itmKaryawan.setVisible(false);
            itmSupplier.setVisible(false);
            mnuTransaksi.setEnabled(true);
            itmTransPembelian.setVisible(false);
            mnuLaporan.setVisible(false);
            mnuAbout.setEnabled(true);
        }
        
    }
    
     private void menuLogout(){
        mnuFile.setEnabled(false);
        mnuMaster.setEnabled(false);
        mnuTransaksi.setEnabled(false);
        mnuLaporan.setEnabled(false);
        mnuAbout.setEnabled(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        itmUbahPswd = new javax.swing.JMenuItem();
        itmLogout = new javax.swing.JMenuItem();
        mnuMaster = new javax.swing.JMenu();
        itmKaryawan = new javax.swing.JMenuItem();
        itmSupplier = new javax.swing.JMenuItem();
        itmPelanggan = new javax.swing.JMenuItem();
        itmBarang = new javax.swing.JMenuItem();
        mnuTransaksi = new javax.swing.JMenu();
        itmTransPembelian = new javax.swing.JMenuItem();
        itmTransPenjualan = new javax.swing.JMenuItem();
        mnuLaporan = new javax.swing.JMenu();
        itmLapPembelian = new javax.swing.JMenuItem();
        itmLapPenjualan = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DeliHerbal POS - Menu Utama");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());
        getContentPane().add(Desktop, new java.awt.GridBagConstraints());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/deliherbalPOS.png"))); // NOI18N
        getContentPane().add(jLabel2, new java.awt.GridBagConstraints());

        mnuFile.setText("File");

        itmUbahPswd.setText("Ubah Password");
        itmUbahPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmUbahPswdActionPerformed(evt);
            }
        });
        mnuFile.add(itmUbahPswd);

        itmLogout.setText("Logout");
        itmLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(itmLogout);

        jMenuBar1.add(mnuFile);

        mnuMaster.setText("Master");
        mnuMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMasterActionPerformed(evt);
            }
        });

        itmKaryawan.setText("Data Karyawan");
        itmKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmKaryawanActionPerformed(evt);
            }
        });
        mnuMaster.add(itmKaryawan);

        itmSupplier.setText("Data Supplier");
        itmSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSupplierActionPerformed(evt);
            }
        });
        mnuMaster.add(itmSupplier);

        itmPelanggan.setText("Data Pelanggan");
        itmPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPelangganActionPerformed(evt);
            }
        });
        mnuMaster.add(itmPelanggan);

        itmBarang.setText("Data Barang");
        itmBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBarangActionPerformed(evt);
            }
        });
        mnuMaster.add(itmBarang);

        jMenuBar1.add(mnuMaster);

        mnuTransaksi.setText("Transaksi");

        itmTransPembelian.setText("Pembelian");
        itmTransPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmTransPembelianActionPerformed(evt);
            }
        });
        mnuTransaksi.add(itmTransPembelian);

        itmTransPenjualan.setText("Penjualan");
        itmTransPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmTransPenjualanActionPerformed(evt);
            }
        });
        mnuTransaksi.add(itmTransPenjualan);

        jMenuBar1.add(mnuTransaksi);

        mnuLaporan.setText("Laporan");

        itmLapPembelian.setText("Pembelian");
        itmLapPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLapPembelianActionPerformed(evt);
            }
        });
        mnuLaporan.add(itmLapPembelian);

        itmLapPenjualan.setText("Penjualan");
        itmLapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLapPenjualanActionPerformed(evt);
            }
        });
        mnuLaporan.add(itmLapPenjualan);

        jMenuBar1.add(mnuLaporan);

        mnuAbout.setText("About");
        mnuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAboutMouseClicked(evt);
            }
        });
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLogoutActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Anda yakin ingin logout?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if (ok == 0){
            this.dispose();
            new login(null, true).show();
        }
    }//GEN-LAST:event_itmLogoutActionPerformed

    private void itmUbahPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUbahPswdActionPerformed
        // TODO add your handling code here:
        new ubahPassword(null,true).show();
    }//GEN-LAST:event_itmUbahPswdActionPerformed

    private void itmKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmKaryawanActionPerformed
        // TODO add your handling code here:
        new user(null,true).show();
    }//GEN-LAST:event_itmKaryawanActionPerformed

    private void itmPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPelangganActionPerformed
        // TODO add your handling code here:
        new pelanggan(null,true).show();
    }//GEN-LAST:event_itmPelangganActionPerformed

    private void itmTransPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmTransPenjualanActionPerformed
        // TODO add your handling code here:
        new transJual(null,true).show();
    }//GEN-LAST:event_itmTransPenjualanActionPerformed

    private void mnuMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMasterActionPerformed

    private void itmSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSupplierActionPerformed
        // TODO add your handling code here:
        new supplier(null,true).show();
    }//GEN-LAST:event_itmSupplierActionPerformed

    private void itmBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBarangActionPerformed
        // TODO add your handling code here:
        new barang(null,true).show();
    }//GEN-LAST:event_itmBarangActionPerformed

    private void itmTransPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmTransPembelianActionPerformed
        // TODO add your handling code here:
        new transBel(null,true).show();
    }//GEN-LAST:event_itmTransPembelianActionPerformed

    private void itmLapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLapPenjualanActionPerformed
        // TODO add your handling code here:
        new lapJual(null,true).show();
    }//GEN-LAST:event_itmLapPenjualanActionPerformed

    private void itmLapPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLapPembelianActionPerformed
        // TODO add your handling code here:
        new lapBeli(null,true).show();
    }//GEN-LAST:event_itmLapPembelianActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar dari aplikasi?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if (ok == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mnuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAboutMouseClicked
        // TODO add your handling code here:
        new about(null,true).show();
    }//GEN-LAST:event_mnuAboutMouseClicked

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        // TODO add your handling code here:
        new about(null,true).show();
    }//GEN-LAST:event_mnuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem itmBarang;
    private javax.swing.JMenuItem itmKaryawan;
    private javax.swing.JMenuItem itmLapPembelian;
    private javax.swing.JMenuItem itmLapPenjualan;
    private javax.swing.JMenuItem itmLogout;
    private javax.swing.JMenuItem itmPelanggan;
    private javax.swing.JMenuItem itmSupplier;
    private javax.swing.JMenuItem itmTransPembelian;
    private javax.swing.JMenuItem itmTransPenjualan;
    private javax.swing.JMenuItem itmUbahPswd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuLaporan;
    private javax.swing.JMenu mnuMaster;
    private javax.swing.JMenu mnuTransaksi;
    // End of variables declaration//GEN-END:variables
}
