/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliherbalpos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author gen781
 */
public class ubahPassword extends javax.swing.JDialog {

    /**
     * Creates new form ubahPassword
     */
    public ubahPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulUbahPass = new javax.swing.JLabel();
        lblPassLama = new javax.swing.JLabel();
        lblPassBaru = new javax.swing.JLabel();
        pwdPassLama = new javax.swing.JPasswordField();
        pwdPassBaru = new javax.swing.JPasswordField();
        btnUbah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblJudulUbahPass.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblJudulUbahPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudulUbahPass.setText("Pengubahan Password");

        lblPassLama.setText("Password Lama");

        lblPassBaru.setText("Password Baru");

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassLama)
                            .addComponent(lblPassBaru))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwdPassBaru)
                            .addComponent(pwdPassLama, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblJudulUbahPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulUbahPass)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassLama)
                    .addComponent(pwdPassLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassBaru)
                    .addComponent(pwdPassBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUbah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if(pwdPassLama.getText().equals("")||pwdPassBaru.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Perhatian",JOptionPane.WARNING_MESSAGE);
        }
        else {
            Connection conn = new koneksi().connect();
            String sql = "SELECT * FROM karyawan WHERE pass=? AND idKar=?";
            try {
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, pwdPassLama.getText());
                ps.setString(2, login.idkar);
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin untuk mengubah Password?","Konfirmasi",JOptionPane.YES_NO_OPTION);
                    try {
                        String sqlupdate="UPDATE karyawan SET pass=? WHERE idKar=?";
                        PreparedStatement psupdate=conn.prepareStatement(sqlupdate);
                        if(ok==0) {
                            try {
                                psupdate.setString(1,pwdPassBaru.getText());
                                psupdate.setString(2,login.idkar);
                                psupdate.executeUpdate();
                                JOptionPane.showMessageDialog(null,"Pengubahan password berhasil","Informasi",JOptionPane.INFORMATION_MESSAGE);
                                this.dispose();
                            }
                            catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "Pengubahan password gagal","Informasi",JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                    }
                    catch (Exception e){}    
                } 
                else{
                    JOptionPane.showMessageDialog(null, "Maaf, Password lama salah","Perhatian",JOptionPane.WARNING_MESSAGE);
                }
            } 
            catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ubahPassword dialog = new ubahPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel lblJudulUbahPass;
    private javax.swing.JLabel lblPassBaru;
    private javax.swing.JLabel lblPassLama;
    private javax.swing.JPasswordField pwdPassBaru;
    private javax.swing.JPasswordField pwdPassLama;
    // End of variables declaration//GEN-END:variables
}
